### ISSUE TITLE
[Question/Suggestion] do missile turrets replace existing normal turrets?

### ISSUE THREAD

**Issue by MasterEvilAce** [Finnerex/MissileTurret#3]
Are missile turrets additional hazards, or do they replace existing normally-spawned turrets?

It would be great (imo) if at random (up to a cap), a specific number of normal turrets were converted to missile turrets. That way the map still controls the difficulty of hazards. Also could work in combination with something like HazardsOutside (a mod which can spawn turrets outside.) Converting just a couple of them (perhaps by recording position/rotation of the original turret, and spawning a missile turret with that same transform) would be super nice.

**Comment by Finnerex** [comment]
Missile turrets do not currently replace normal turrets. I don't think that they should because I don't necessarily want to lower the spawns of normal turrets. I do want to work more on the spawning mechanics and this could be an option, but I definitely want to make them more dynamic somehow. 
I tested and it does work with HazardsOutside.
