### ISSUE TITLE
Missile issue

### ISSUE THREAD

**Issue by sweatychickleg** [Finnerex/MissileTurret#5]
The missiles were clipping through the ground and never disappeared. They kept flying in circles around me and followed me to the next moon and I had to quit out the game to get them to finally stop harrassing me. Is it a compatibility issue with other mods or is it a bug within this mod?

**Comment by Finnerex** [comment]
Thanks for the bug report!
I need some more information to figure out the issue.
What version of the mod were you using?
Were you the host or a client when this happened?
Are you able to reproduce this issue? (in the latest version if you aren't using that)
If you can, please tell me any specific conditions that might be relevant and send any red text from the console.

If anyone else encounters the same issue I would appreciate the same information.
Thanks in advance!

**Comment by larsthorwell** [comment]
had the same thing happen to me. using the most recent version of the mod, i dodged the missile into another room and it just started circling me. maybe add a timer to explode in the air if it is homing for too long to avoid this issue? maybe like a 7 second timer before the missile just blows up in the air, or have it blow up when it hits a solid object, because it was phasing through the walls and floor. i might have the outplayed footage of it happening if you are interested, i can check if you need me to.

**Comment by Finnerex** [comment]
The missiles do have this timer. Unfortunately I think the error you are experiencing also affects this feature and stops it from working. I would like to see the footage if you can get it. Also let me know if this keeps happening / any other information you deem important.

**Comment by larsthorwell** [comment]
ok ill go look for i now, will update if i can see it.

**Comment by larsthorwell** [comment]
video is too long for github, try to dm me on discord and ill try to send you the vid there. my discord is Larsthorwell.
